export const EMPTY_STRING = '';

export const VALIDATION_CONFIG = {
  MIN_LENGTH_STRING: 3,
  MEDIUM_LENGTH_STRING: 100,
  MAX_LENGTH_STRING: 255,
  LENGTH_STRING: 8,
  MIN_LENGTH_NUMBER: 1,
  MIN_LENGTH_LOW_CASE: 1,
  MIN_LENGTH_UP_CASE: 1,
  MIN_SYMBOL: 1,
};

export const DEFAULT_TIME_OUT = 10000; // 10 seconds
